spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/documents_db
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  workers:
    enabled: true
    batch-size: 20
    submit-interval-ms: 3000
    approve-interval-ms: 3000
    submit-max-batches-per-run: 5
    approve-max-batches-per-run: 5
